url: "https://dev.covidtracker.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Covidtracker"
tagline: "Statistiques et visualisations de données Covid19"
defaults:
 - scope:
     path: "assets/img"
   values:
     image: true
lang: fr
sass:
 load_paths:
  - _sass
  - node_modules

exclude:
 - node_modules
 - LICENSE.txt
 - Makefile
 - README.md
 - package.json
 - package-lock.json
 - yarn.lock
 - deploy_npm.sh
 - .idea

collections:
 posts:
  output: true
  permalink: /news/:categories/:year/:month/:day/:title/

twitter:
 username: CovidTracker_fr
 card: summary

page_gen-dirs: true
page_gen:
 - data: 'departements'
   template: 'departement'
   dir: 'syntheses/departement'
   name: 'dep_name'
   index_files: false

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 480
      quality: 80
    - width: 800
      quality: 90
    - width: 1400
      quality: 90
    - width: 1900
      quality: 90
  strip: true
  save_to_source: false

plugins:
 - jekyll-seo-tag


